apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minhaapp
  template:
    metadata:
      labels:
        app: minhaapp
    spec:
      containers:
      - name: minhaapp
        image: physyx/minhaapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: minhaapp-service
spec:
  type: NodePort
  selector:
    app: minhaapp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
