orbs:
  docker: circleci/docker@2.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - docker/login:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
      - run: docker build -t physyx/minhaapp:latest .
      - run: docker push physyx/minhaapp:latest
