version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t physyx/minhaapp:latest .
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - run:
          name: Push Docker image
          command: docker push physyx/minhaapp:latest
