version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t physyx/minhaapp:latest .
      - run:
          name: Docker login
          command: echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Push image
          command: docker push physyx/minhaapp:latest

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push
